### PR TITLE
Refactor for latest fable CLI tool

### PR DESCRIPTION
**Pull request by dbrattli**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks @dbrattli! In my machine, `pip` command doesn't work, `python -m pip` does. Does this work for all Python installations, can it be used instead?

Still concerned this looks like a step backwards in terms of user experience. What was a single line command that run more or less fast, now requires multiple commands and takes considerably longer, and we need to run a full Fable build just to generate the `requirements.txt`. If there's no way to decide automatically if these steps can be skipped, the build script will have to run them every time. Consider for example this breaks some Fable optimizations, because `dotnet fable` compiles in RELEASE mode by default while `dotnet fable watch` does it in DEBUG mode, this means each compilation overwrites the files of the other and they cannot be reused (see [blog post](https://fable.io/blog/2022/2022-01-09-Faster-compilation-Fable-3-7.html)).

Also concerned about the pitfalls of packages with Python. Some questions:

- Is my understanding correct that Pip installs packages globally? Does this mean that if we have two Fable Python projects in the machine which use different Fable versions, every time we run `pip install -r requirements.txt` it breaks the other project?
- If we want to go with Poetry, why sometimes Pip and not Poetry all the way?
- What happens if users have their own `requirements.txt` file for Python dependencies? Is it ok to have one "hidden" requirements file for Fable dependencies and another for Python ones.

Summoning @ncave now because I believe Fable Rust takes a similar approach and installs fable-library as if it was a Cargo dependency, so maybe they can provide some insights. Not sure if these problems have been addressed in Rust though, how will Fable packages be dealt with? What happens if the user edits the automatically generated Cargo.toml?

**Comment by ncave** [comment]
@alfonsogarciacaro I'm not sure if `fable-library-rust` offers any insights for Python. Although it can be published as a package (crate) and versioned, the `fable` tool copies it locally to the output folder and that's enough to reference it from the Rust project file `Cargo.toml` (also, this way it's always up to date and matches the compiler version exactly).

**Comment by alfonsogarciacaro** [comment]
@ncave Yes, sorry. Part of the discussion was private so I haven't given all the details 😅 In principle, Python will work the same way. The fable-library (and other packages) files are copied locally to the `fable_modules` folder, but then @dbrattli plans to instruct Python (either with Pip or Poetry, a Python package manager closer to Paket) to install them as if there were packages. The generated `requirements.txt` file here looks like this:

```
-e ./fable_modules/fable-library
-e ./fable_modules/fable-python
```

The main difference is by default Pip doesn't install packages per project but per machine, so I'm afraid this operation could potentially interfere with other Fable Python projects in the machine. Although I'm not entirely sure how Pip works, so I may be wrong.

BTW, how will Fable packages installed from Nuget work in a Fable Rust project?

**Comment by ncave** [comment]
@alfonsogarciacaro I see, in Rust you can just reference a local package by path and it just works.

> how will Fable packages installed from Nuget work in a Fable Rust project?

I imagine the same way it does with JavaScript, i.e. nuget packages containing sources will be compiled as part of the project and go in the outDir folder.

**Comment by dbrattli** [comment]
@alfonsogarciacaro Yes, you are right that it installs per machine (not project). You probably already did the same thing with the pandas package without complaining. But the Python solution for not interfering with other solutions is to use [virtual environments](https://docs.python.org/3/tutorial/venv.html), and (again) [poetry](https://python-poetry.org/) is a great solution for this. The problem here is that you're using Python as as super simple demo script and expect that all dependencies (and virtual environments) should be taken care of by fable. That's not how things usually works in Python. Python beyond a simple script have all these problems, and they are solved using packages and virtual environments. You may not like it, but for me that should also be our default starting point. Not that fable should make a mega fable_module bundle containing every module just because you want Python to look like JS. No other Python developer would except such as solution. So it's may be a step back for a demo script, but a step forward for using fable in a real Python project. 

Some answers:

- I used pip since you most likely had already used pip to install the pandas module
- If you are concerned about interference with other projects, you should use virtual environments
- There are many ways to handle virtual environments in Python. I recommend using poetry. 
- The requirements.txt file simply lists the packages generated by fable. It doesn't have anything to do with Python, pip or any other requirements.txt file. You can have as many such files as you like and you may pip install their contents if you like (or not).
- The RELEASE vs DEBUG mode is problem, but it's only a problem when using `watch` for demos. It's not a problem for a real project. Could you just add `-c DEBUG` to the first run?

We could go poetry all the way and have fable update your pyproject.toml file with the generated dependencies. This will still not work live during watch since you need to do a `poetry update` afterwards. But Python do not usually enforce poetry (or virtual environments). It's up to the user to decide what package manager or virtual environments they want to use (or not).

**Comment by dbrattli** [comment]
FYI: `pip` by default installs per machine. `pip` in a virtual environment installs per project (or environment be be more correct. A user or project may have several environments). So it's your own responsibility to use virtual environments (or not).

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your reply @dbrattli! Python compilation is your work and I trust your judgement :+1: I'm just trying to bring in the experience of Fable development in case it helps (particularly from the early versions when we had very similar discussions), but I don't want to impose anything :)  A lot for work was done to simplify the commands and to speed up the bootstrap (this is what users liked most of Fable 3) that's why I was thinking how we could avoid the "double build".

You're absolutely right that using a global "pandas" installation in the sample ruins the points I was making above 😅 I guess the main difference is the API of so widely-used packages as pandas is very stable, while fable-library can break at any time if, for example, we decide to change the way unions are compiled to increase performance.

> Not that fable should make a mega fable_module bundle containing every module just because you want Python to look like JS. No other Python developer would except such as solution. 

This is probably my biggest misunderstanding, because at this point it looks like we will still have the fable_modules folder in all projects and the only difference is there will be less relative paths imports in the generated .py files. If we manage to enforce the version of the fable-library per project, it should be easy to publish a new version per Fable release. But this gets more complicated with packages we don't control.

Actually, I would love if we could find a way to distribute Fable packages in precompiled form, this would speed up compilation of projects with big Fable dependencies. But as we talked, it will be challenging to ensure the distributed files are compiled with a specific version of Fable (I've sometimes thought of creating a local cache in the system for this purpose). Also, when .fs sources are missing getting the file paths and inline functions is tricky. I managed to solve this partially with the precompilation feature last year, but it probably requires more work and testing if we were to expand this to all Fable packages.

**Comment by dbrattli** [comment]
@alfonsogarciacaro I've decided to revert the latest package changes until we can find a better solution for this. I.e. go back to plain modules within `fable_modules`.

**Pull request closed without merging**
